---
- name: Change port number 
  ignore_errors: true
  hosts: all 
  tasks: 
    - name: Change /etc/ssh/sshd_config
      lineinfile: 
        path: /etc/ssh/sshd_config
        regexp: '^#Port 22'
        line:  'Port 7789'

    - name: Restart sshd  on Centos 6 
      when: ansible_distribution_major_version == "6"
      service: 
        name: sshd 
        state: restarted

    - name: Restart sshd  on Centos 7 
      when: ansible_distribution_major_version == "7"
      systemd: 
        name: sshd 
        state: restarted



